development:
  username: root
  adapter: mysql
  database: bta_development
  host: localhost
  password: ''
test:
  username: root
  adapter: mysql
  database: bta_test
  host: localhost
  password: ''
production: 
  username: root
  adapter: mysql
  database: bta_production
  host: localhost
  password: ''

