Tramlines.add_plugin(:blog)
Tramlines.add_plugin(:enquiries)
Tramlines.add_plugin(:facebook_connect)
Tramlines.add_plugin(:events)
Tramlines.add_plugin(:forum)
Tramlines.add_plugin(:locations)
Tramlines.add_plugin(:mobile)
Tramlines.add_plugin(:walls)
