photo_resize_geometry: 780x
site_name: British Tinnitus Association
site_url: http://bta.yoomee.com
site_slogan: 
site_email: info@yoomee.com
webthumb_key: ff1e5c1f36807f9e87868f9c01c33dbb
development:
  site_name: British Tinnitus Association