photo_resize_geometry: 780x
site_name: British Tinnitus Association
site_url: http://www.tinnitus.org.uk
site_slogan: 
site_email: info@tinnitus.org.uk
google_analytics: UA-20658651-1
webthumb_key: ff1e5c1f36807f9e87868f9c01c33dbb
development:
  site_name: British Tinnitus Association
production:
  # This needs changing before go-live
  paypal_business_email: jane@tinnitus.org.uk
